plugins {
    id 'com.android.application'
}

android {
    namespace 'ch.piiwii.waarchive'
    compileSdk 35

    defaultConfig {
        applicationId 'ch.piiwii.waarchive'
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName '0.4.3'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
