package ch.piiwii.roadbookgeneve;
import android.app.*;import android.content.*;import android.os.Build;
public final class AlarmScheduler{
 public static final String PREF_ENABLED="alerts_enabled"; private AlarmScheduler(){}
 public static boolean isEnabled(Context c){return Itinerary.prefs(c).getBoolean(PREF_ENABLED,false);} public static void setEnabled(Context c,boolean e){Itinerary.prefs(c).edit().putBoolean(PREF_ENABLED,e).apply();if(e)scheduleAll(c);else cancelAll(c);} public static boolean canExact(Context c){if(Build.VERSION.SDK_INT<31)return true;AlarmManager a=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);return a!=null&&a.canScheduleExactAlarms();}
 public static void scheduleAll(Context c){cancelAll(c);if(!isEnabled(c))return;int i=0;for(Itinerary.Stop s:Itinerary.STOPS){long at=Itinerary.getTimeMillis(c,s);if(s.alertBeforeMinutes>0)schedule(c,at-s.alertBeforeMinutes*60000L,1000+i*2,"Dans "+s.alertBeforeMinutes+" min",s.title+" à "+Itinerary.getTime(c,s));if(s.alertAtTime)schedule(c,at,1001+i*2,s.title,msg(s));i++;}}
 private static String msg(Itinerary.Stop s){if("depart_sion".equals(s.id))return"C'est l'heure de partir vers Rolle.";if("leave_rolle".equals(s.id))return"Direction Genève / P+R Bachet-Praille.";if("leave_village".equals(s.id))return"Pars maintenant vers le centre pour garder ta marge.";if("garden".equals(s.id))return"Objectif: être placé au Jardin Anglais.";if("rock".equals(s.id))return"La séance Rock & Pop commence maintenant.";if("choice".equals(s.id))return"22h20: choisis la suite selon la motivation.";return s.note;}
 private static void schedule(Context c,long t,int code,String title,String text){if(t<=System.currentTimeMillis())return;AlarmManager a=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(a==null)return;Intent in=new Intent(c,AlarmReceiver.class).putExtra("title",title).putExtra("text",text).putExtra("notification_id",code);PendingIntent p=PendingIntent.getBroadcast(c,code,in,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);if(Build.VERSION.SDK_INT>=31&&!a.canScheduleExactAlarms())a.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,t,p);else a.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,t,p);}
 public static void cancelAll(Context c){AlarmManager a=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(a==null)return;for(int i=0;i<Itinerary.STOPS.length;i++){cancel(c,a,1000+i*2);cancel(c,a,1001+i*2);}} private static void cancel(Context c,AlarmManager a,int code){PendingIntent p=PendingIntent.getBroadcast(c,code,new Intent(c,AlarmReceiver.class),PendingIntent.FLAG_NO_CREATE|PendingIntent.FLAG_IMMUTABLE);if(p!=null){a.cancel(p);p.cancel();}}
}
