package ch.piiwii.roadbookgeneve;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.Locale;

public class MainActivity extends Activity{
 private final Handler h=new Handler(); private TextView nextTitle,countdown,nextTime,status; private LinearLayout timeline; private boolean ready=false;
 private static final int BG=Color.rgb(10,16,26),CARD=Color.rgb(23,32,46),ALT=Color.rgb(31,42,58),TEXT=Color.rgb(243,246,251),MUTED=Color.rgb(166,177,194),ACCENT=Color.rgb(255,183,77),GREEN=Color.rgb(88,214,141),BLUE=Color.rgb(97,175,239);
 private int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);} private GradientDrawable round(int c,float r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;} private TextView tv(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setIncludeFontPadding(false);return v;} private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setMinHeight(0);b.setMinimumHeight(0);b.setBackground(round(Color.rgb(46,62,82),12));return b;} private LinearLayout.LayoutParams mw(){return new LinearLayout.LayoutParams(-1,-2);}
 @Override public void onCreate(Bundle b){super.onCreate(b);AlarmReceiver.createChannel(this);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);ScrollView sc=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(18),dp(16),dp(30));
  TextView k=tv("SAMEDI 29 AOÛT 2026",12,ACCENT);k.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(k,mw());TextView t=tv("Roadbook Genève",30,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);LinearLayout.LayoutParams lp=mw();lp.topMargin=dp(5);c.addView(t,lp);TextView sub=tv("Sion → Rolle → Geneva RP → Rêve d'Eau",15,MUTED);lp=mw();lp.topMargin=dp(4);lp.bottomMargin=dp(16);c.addView(sub,lp);
  LinearLayout nc=new LinearLayout(this);nc.setOrientation(LinearLayout.VERTICAL);nc.setPadding(dp(18),dp(16),dp(18),dp(16));nc.setBackground(round(ALT,18));TextView nl=tv("PROCHAINE ÉTAPE",11,GREEN);nl.setTypeface(Typeface.DEFAULT,Typeface.BOLD);nc.addView(nl,mw());nextTitle=tv("—",20,TEXT);nextTitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);lp=mw();lp.topMargin=dp(8);nc.addView(nextTitle,lp);countdown=tv("—",34,ACCENT);countdown.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);lp=mw();lp.topMargin=dp(8);nc.addView(countdown,lp);nextTime=tv("",13,MUTED);nc.addView(nextTime,mw());c.addView(nc,mw());
  LinearLayout ac=new LinearLayout(this);ac.setOrientation(LinearLayout.VERTICAL);ac.setPadding(dp(16),dp(14),dp(16),dp(14));ac.setBackground(round(CARD,16));lp=mw();lp.topMargin=dp(12);TextView at=tv("Rappels de départ",17,TEXT);at.setTypeface(Typeface.DEFAULT,Typeface.BOLD);ac.addView(at,mw());status=tv("",13,MUTED);ac.addView(status,mw());LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button en=btn("Activer / reprogrammer");en.setBackground(round(Color.rgb(45,119,83),12));en.setOnClickListener(v->enableAlerts());row.addView(en,new LinearLayout.LayoutParams(0,dp(44),1));Button test=btn("Test");LinearLayout.LayoutParams tlp=new LinearLayout.LayoutParams(dp(78),dp(44));tlp.leftMargin=dp(8);test.setOnClickListener(v->testNotif());row.addView(test,tlp);LinearLayout.LayoutParams rlp=mw();rlp.topMargin=dp(10);ac.addView(row,rlp);Button dis=btn("Désactiver les rappels");lp=mw();lp.topMargin=dp(8);lp.height=dp(42);dis.setOnClickListener(v->{AlarmScheduler.setEnabled(this,false);updateStatus();Toast.makeText(this,"Rappels désactivés",Toast.LENGTH_SHORT).show();});ac.addView(dis,lp);c.addView(ac,lp=mw());lp.topMargin=dp(12);
  TextView pt=tv("Programme",22,TEXT);pt.setTypeface(Typeface.DEFAULT,Typeface.BOLD);lp=mw();lp.topMargin=dp(24);lp.bottomMargin=dp(10);c.addView(pt,lp);timeline=new LinearLayout(this);timeline.setOrientation(LinearLayout.VERTICAL);c.addView(timeline,mw());rebuild();addChoices(c);TextView foot=tv("Les trajets gardent de la marge. Rock & Pop reste l'objectif fixe de 22h00.",12,MUTED);foot.setGravity(Gravity.CENTER);lp=mw();lp.topMargin=dp(20);c.addView(foot,lp);sc.addView(c,new ScrollView.LayoutParams(-1,-2));root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);ready=true;updateStatus();h.post(tick);}
 private void rebuild(){timeline.removeAllViews();for(Itinerary.Stop s:Itinerary.STOPS)addStop(s);} private void addStop(Itinerary.Stop s){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(15),dp(14),dp(15),dp(14));card.setBackground(round(CARD,16));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView tm=tv(Itinerary.getTime(this,s),22,s.fixedEvent?ACCENT:BLUE);tm.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);top.addView(tm,new LinearLayout.LayoutParams(dp(76),-2));TextView tt=tv(s.title,16,TEXT);tt.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(tt,new LinearLayout.LayoutParams(0,-2,1));card.addView(top,mw());TextView n=tv(s.note,13,MUTED);LinearLayout.LayoutParams lp=mw();lp.topMargin=dp(7);card.addView(n,lp);if(s.fixedEvent){TextView f=tv("Horaire événement",11,ACCENT);f.setTypeface(Typeface.DEFAULT,Typeface.BOLD);card.addView(f,mw());}LinearLayout a=new LinearLayout(this);if(s.destination!=null){Button g=btn("GPS");g.setBackground(round(Color.rgb(38,102,155),11));g.setOnClickListener(v->nav(s.destination));a.addView(g,new LinearLayout.LayoutParams(0,dp(42),1));}Button e=btn("Modifier l'heure");LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(0,dp(42),1);if(s.destination!=null)ep.leftMargin=dp(7);e.setOnClickListener(v->edit(s));a.addView(e,ep);lp=mw();lp.topMargin=dp(10);card.addView(a,lp);lp=mw();lp.bottomMargin=dp(9);timeline.addView(card,lp);}
 private void edit(Itinerary.Stop s){String[]p=Itinerary.getTime(this,s).split(":");new TimePickerDialog(this,(v,hh,mm)->{Itinerary.setTime(this,s,hh,mm);if(AlarmScheduler.isEnabled(this))AlarmScheduler.scheduleAll(this);rebuild();updateCount();Toast.makeText(this,"Horaire mis à jour",Toast.LENGTH_SHORT).show();},Integer.parseInt(p[0]),Integer.parseInt(p[1]),true).show();}
 private void addChoices(LinearLayout c){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(16),dp(16),dp(16),dp(16));card.setBackground(round(Color.rgb(37,30,55),18));TextView t=tv("Après 22h20 — selon la motivation",19,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);card.addView(t,mw());TextView d=tv("Aucun retour imposé. Tu choisis sur le moment.",13,MUTED);card.addView(d,mw());Button stay=btn("💦 Rester pour le Classique de 22h30");stay.setOnClickListener(v->{Itinerary.prefs(this).edit().putBoolean("stay_classic",true).apply();updateCount();Toast.makeText(this,"Option 22h30 retenue",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams lp=mw();lp.height=dp(48);lp.topMargin=dp(10);card.addView(stay,lp);Button home=btn("🏠 GPS → Sion");home.setOnClickListener(v->{Itinerary.prefs(this).edit().putBoolean("stay_classic",false).apply();nav("Sion, Suisse");});lp=mw();lp.height=dp(48);lp.topMargin=dp(8);card.addView(home,lp);EditText other=new EditText(this);other.setSingleLine(true);other.setHint("Autre sortie / lieu…");other.setHintTextColor(Color.GRAY);other.setTextColor(TEXT);other.setText(Itinerary.prefs(this).getString("other_destination",""));lp=mw();lp.height=dp(48);lp.topMargin=dp(8);card.addView(other,lp);Button go=btn("🧭 GPS → cette destination");go.setOnClickListener(v->{String x=other.getText().toString().trim();if(x.isEmpty()){Toast.makeText(this,"Entre d'abord le lieu",Toast.LENGTH_SHORT).show();return;}Itinerary.prefs(this).edit().putString("other_destination",x).putBoolean("stay_classic",false).apply();nav(x);});lp=mw();lp.height=dp(48);lp.topMargin=dp(8);card.addView(go,lp);lp=mw();lp.topMargin=dp(20);c.addView(card,lp);}
 private void enableAlerts(){AlarmScheduler.setEnabled(this,true);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},501);if(Build.VERSION.SDK_INT>=31&&!AlarmScheduler.canExact(this)){try{startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM,Uri.parse("package:"+getPackageName())));Toast.makeText(this,"Autorise Alarmes et rappels puis reviens.",Toast.LENGTH_LONG).show();}catch(Exception e){AlarmScheduler.scheduleAll(this);}}else{AlarmScheduler.scheduleAll(this);Toast.makeText(this,"Rappels programmés",Toast.LENGTH_SHORT).show();}updateStatus();}
 private void testNotif(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},502);return;}sendBroadcast(new Intent(this,AlarmReceiver.class).putExtra("title","Test Roadbook Genève").putExtra("text","Parfait: les notifications fonctionnent.").putExtra("notification_id",9090));}
 private void updateStatus(){if(status==null)return;if(!AlarmScheduler.isEnabled(this)){status.setText("Désactivés. Active-les avant de partir.");status.setTextColor(MUTED);}else if(Build.VERSION.SDK_INT>=31&&!AlarmScheduler.canExact(this)){status.setText("Actifs en mode souple. Autorise Alarmes et rappels pour la précision maximale.");status.setTextColor(ACCENT);}else{status.setText("Actifs • rappels avant les départs + aux heures clés");status.setTextColor(GREEN);}}
 private void nav(String dest){try{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("google.navigation:q="+Uri.encode(dest)));i.setPackage("com.google.android.apps.maps");startActivity(i);}catch(Exception e){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/maps/dir/?api=1&destination="+Uri.encode(dest))));}}
 private final Runnable tick=new Runnable(){public void run(){updateCount();h.postDelayed(this,1000);}}; private void updateCount(){if(nextTitle==null)return;long now=System.currentTimeMillis(),best=Long.MAX_VALUE;Itinerary.Stop next=null;boolean stay=Itinerary.prefs(this).getBoolean("stay_classic",false);for(Itinerary.Stop s:Itinerary.STOPS){if("classic".equals(s.id)&&!stay)continue;long w=Itinerary.getTimeMillis(this,s);if(w>=now&&w<best){best=w;next=s;}}if(next==null){nextTitle.setText("Fin de soirée libre");countdown.setText("À vous de voir 😎");countdown.setTextSize(24);nextTime.setText("Retour Sion, autre sortie, ou prolongation.");return;}countdown.setTextSize(34);nextTitle.setText(next.title);long sec=Math.max(0,best-now)/1000,d=sec/86400,hh=(sec%86400)/3600,mm=(sec%3600)/60,ss=sec%60;countdown.setText(d>0?String.format(Locale.ROOT,"%dj %02d:%02d:%02d",d,hh,mm,ss):String.format(Locale.ROOT,"%02d:%02d:%02d",hh,mm,ss));nextTime.setText("Prévu à "+Itinerary.getTime(this,next)+" • heure Suisse");}
 @Override protected void onResume(){super.onResume();if(AlarmScheduler.isEnabled(this))AlarmScheduler.scheduleAll(this);if(ready){updateStatus();updateCount();}}@Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(AlarmScheduler.isEnabled(this))AlarmScheduler.scheduleAll(this);updateStatus();}@Override protected void onDestroy(){h.removeCallbacks(tick);super.onDestroy();}
}
