from pathlib import Path

root=Path(__file__).resolve().parents[1]
java=root/'android/app/src/main/java/ch/piiwii/modeconvoi'
main_path=java/'MainActivity.java'
map_path=root/'android/app/src/main/assets/convoy_map.html'
gradle_path=root/'android/app/build.gradle'
api_path=java/'ConvoyApi.java'

def once(text, old, new, label):
    n=text.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1 anchor, found {n}')
    return text.replace(old,new,1)

main=main_path.read_text()
old_avatar='''    private View participantAvatar(JSONObject p,int size,int fallbackColor){\n        String image=p==null?prefs.get("profileVehicleImage",""):p.optString("vehicleImage","");\n        if(image!=null&&!image.isEmpty()){\n            try{Bitmap b=VehicleImageCache.decode(image);if(b!=null){ImageView iv=new ImageView(this);iv.setScaleType(ImageView.ScaleType.CENTER_CROP);iv.setImageBitmap(b);iv.setBackground(roundBg(control,participantMarkerColor(p,fallbackColor),size/2,1));iv.setClipToOutline(true);return iv;}}catch(Exception ignored){}\n        }\n        String icon=p==null?prefs.get("profileVehicleIcon","🚗"):p.optString("vehicleIcon","🚗");if(icon.isEmpty())icon="🚗";\n        TextView v=text(icon,size>=46?24:19,false,participantMarkerColor(p,fallbackColor));v.setGravity(Gravity.CENTER);v.setBackground(roundBg(control,participantMarkerColor(p,fallbackColor),size/2,1));return v;\n    }\n'''
new_avatar='''    private View participantAvatar(JSONObject p,int size,int fallbackColor){\n        String image=p==null?prefs.get("profileVehicleImage",""):p.optString("vehicleImage","");\n        if(image!=null&&!image.isEmpty()){\n            try{\n                Bitmap b=VehicleImageCache.decode(image);\n                if(b!=null){\n                    boolean transparentVehicle=image.startsWith("iVBOR");\n                    ImageView iv=new ImageView(this);\n                    iv.setScaleType(transparentVehicle?ImageView.ScaleType.FIT_CENTER:ImageView.ScaleType.CENTER_CROP);\n                    iv.setPadding(transparentVehicle?dp(3):0,transparentVehicle?dp(3):0,transparentVehicle?dp(3):0,transparentVehicle?dp(3):0);\n                    iv.setImageBitmap(b);\n                    iv.setBackground(roundBg(control,participantMarkerColor(p,fallbackColor),size/2,1));\n                    iv.setClipToOutline(!transparentVehicle);\n                    return iv;\n                }\n            }catch(Exception ignored){}\n        }\n        String icon=p==null?prefs.get("profileVehicleIcon","🚗"):p.optString("vehicleIcon","🚗");if(icon.isEmpty()||VolkswagenIconPack.isVolkswagen(icon))icon="🚗";\n        TextView v=text(icon,size>=46?24:19,false,participantMarkerColor(p,fallbackColor));v.setGravity(Gravity.CENTER);v.setBackground(roundBg(control,participantMarkerColor(p,fallbackColor),size/2,1));return v;\n    }\n'''
main=once(main,old_avatar,new_avatar,'participant avatar')
old_vw='''        // Emplacements réservés au futur pack d'icônes Volkswagen.\n        LinearLayout vwHeader=new LinearLayout(this);vwHeader.setGravity(Gravity.CENTER_VERTICAL);vwHeader.setPadding(0,dp(10),0,dp(3));\n        TextView vwTitle=text("ICÔNES VOLKSWAGEN",11,true,accent);vwHeader.addView(vwTitle,new LinearLayout.LayoutParams(0,dp(40),1));\n        TextView vwChevron=text("⌄",22,true,accent);vwChevron.setGravity(Gravity.CENTER);vwHeader.addView(vwChevron,new LinearLayout.LayoutParams(dp(44),dp(40)));box.addView(vwHeader);\n        GridLayout vwFirst=new GridLayout(this);vwFirst.setColumnCount(5);\n        GridLayout vwMore=new GridLayout(this);vwMore.setColumnCount(5);vwMore.setVisibility(View.GONE);\n        for(int i=0;i<10;i++){\n            TextView slot=text("",18,false,muted);slot.setGravity(Gravity.CENTER);slot.setBackground(roundBg(control,border,12,1));slot.setAlpha(.55f);\n            GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=dp(54);lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(dp(3),dp(3),dp(3),dp(3));\n            (i<5?vwFirst:vwMore).addView(slot,lp);\n        }\n        box.addView(vwFirst,new LinearLayout.LayoutParams(-1,-2));box.addView(vwMore,new LinearLayout.LayoutParams(-1,-2));\n        TextView vwHint=text("Emplacements réservés au futur pack Volkswagen.",11,false,muted);vwHint.setPadding(dp(4),dp(3),dp(4),0);box.addView(vwHint);\n        vwHeader.setOnClickListener(v->{boolean open=vwMore.getVisibility()==View.VISIBLE;vwMore.setVisibility(open?View.GONE:View.VISIBLE);vwChevron.setText(open?"⌄":"⌃");});\n'''
new_vw='''        LinearLayout vwHeader=new LinearLayout(this);vwHeader.setGravity(Gravity.CENTER_VERTICAL);vwHeader.setPadding(0,dp(10),0,dp(3));\n        TextView vwTitle=text("ICÔNES VOLKSWAGEN",11,true,accent);vwHeader.addView(vwTitle,new LinearLayout.LayoutParams(0,dp(40),1));\n        TextView vwChevron=text("⌄",22,true,accent);vwChevron.setGravity(Gravity.CENTER);vwHeader.addView(vwChevron,new LinearLayout.LayoutParams(dp(44),dp(40)));box.addView(vwHeader);\n        GridLayout vwFirst=new GridLayout(this);vwFirst.setColumnCount(5);\n        GridLayout vwMore=new GridLayout(this);vwMore.setColumnCount(5);vwMore.setVisibility(View.GONE);\n        VolkswagenIconPack.Item[] vwItems=VolkswagenIconPack.items();\n        String selectedVehicleIcon=prefs.get("profileVehicleIcon","🚗");\n        for(int i=0;i<vwItems.length;i++){\n            final VolkswagenIconPack.Item item=vwItems[i];\n            FrameLayout slot=new FrameLayout(this);slot.setContentDescription(item.label);\n            boolean selected=item.id.equals(selectedVehicleIcon);\n            slot.setBackground(roundBg(control,selected?accent:border,12,selected?2:1));\n            ImageView carIcon=new ImageView(this);carIcon.setScaleType(ImageView.ScaleType.FIT_CENTER);carIcon.setPadding(dp(4),dp(4),dp(4),dp(4));carIcon.setImageBitmap(item.bitmap());\n            slot.addView(carIcon,new FrameLayout.LayoutParams(-1,-1));\n            slot.setOnClickListener(v->{prefs.put("profileVehicleIcon",item.id);prefs.put("profileVehicleImage",item.base64());refreshVehiclePreview();});\n            GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=dp(58);lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(dp(3),dp(3),dp(3),dp(3));\n            (i<5?vwFirst:vwMore).addView(slot,lp);\n        }\n        box.addView(vwFirst,new LinearLayout.LayoutParams(-1,-2));box.addView(vwMore,new LinearLayout.LayoutParams(-1,-2));\n        TextView vwHint=text("10 modèles Volkswagen · appuie sur une voiture pour l'utiliser sur la carte.",11,false,muted);vwHint.setPadding(dp(4),dp(3),dp(4),0);box.addView(vwHint);\n        vwHeader.setOnClickListener(v->{boolean open=vwMore.getVisibility()==View.VISIBLE;vwMore.setVisibility(open?View.GONE:View.VISIBLE);vwChevron.setText(open?"⌄":"⌃");});\n'''
main=once(main,old_vw,new_vw,'Volkswagen picker')
main=once(main,'Mode Convoi 0.3.38','Mode Convoi 0.3.39','about version')
main_path.write_text(main)

m=map_path.read_text()
m=once(m,'.marker{position:absolute;transform:translate(-18px,-18px);z-index:5;pointer-events:auto}.car{font-size:25px;filter:drop-shadow(0 2px 3px #000)}.photo{width:34px;height:34px;border-radius:50%;object-fit:cover;border:2px solid #fff;box-shadow:0 2px 5px #000a;background:#222}',
'''.marker{position:absolute;transform:translate(-18px,-18px);z-index:5;pointer-events:auto}.car{font-size:25px;filter:drop-shadow(0 2px 3px #000)}.photo{width:34px;height:34px;border-radius:50%;object-fit:cover;border:2px solid #fff;box-shadow:0 2px 5px #000a;background:#222}.vehicle-art{width:42px;height:42px;object-fit:contain;filter:drop-shadow(0 2px 3px #000b);background:transparent}''','map vehicle css')
m=once(m,"let zoom=10, center={lat:46.23,lon:7.36}, state={}, myId='', fitted=false, tileErrors=0, dragging=false, startX=0,startY=0,startWorld=null;",
"let zoom=10, center={lat:46.23,lon:7.36}, state={}, myId='', fitted=false, tileErrors=0, dragging=false, startX=0,startY=0,startWorld=null,lastDX=0,lastDY=0;",'drag state')
old_add='''function addMarker(lat,lon,label,kind='',stale=false,icon='🚗',image='',markerColor=''){if(!validPoint(lat,lon))return;const tl=topLeft(),p=project(lat,lon),m=document.createElement('div');m.className='marker '+kind+(stale?' stale':'');m.style.left=(p.x-tl.x)+'px';m.style.top=(p.y-tl.y)+'px';const safeImg=(image&&/^[A-Za-z0-9+/=]+$/.test(image)&&image.length<30000)?image:'';const visual=kind.includes('rally')?'<div class="car">📍</div>':(safeImg?`<img class="photo" src="data:image/jpeg;base64,${safeImg}">`:`<div class="car">${esc(icon||'🚗')}</div>`);m.innerHTML=`${visual}<div class="label">${esc(label)}</div>`;if(markerColor&&/^#[0-9A-Fa-f]{6}$/.test(markerColor)){const lab=m.querySelector('.label');if(lab)lab.style.borderColor=markerColor;const ph=m.querySelector('.photo');if(ph)ph.style.borderColor=markerColor;}markersEl.appendChild(m)}'''
new_add='''function addMarker(lat,lon,label,kind='',stale=false,icon='🚗',image='',markerColor=''){if(!validPoint(lat,lon))return;const tl=topLeft(),p=project(lat,lon),m=document.createElement('div');m.className='marker '+kind+(stale?' stale':'');m.style.left=(p.x-tl.x)+'px';m.style.top=(p.y-tl.y)+'px';const safeImg=(image&&/^[A-Za-z0-9+/=]+$/.test(image)&&image.length<30000)?image:'';const png=safeImg.startsWith('iVBOR');const visual=kind.includes('rally')?'<div class="car">📍</div>':(safeImg?`<img class="${png?'vehicle-art':'photo'}" src="data:image/${png?'png':'jpeg'};base64,${safeImg}">`:`<div class="car">${esc(icon||'🚗')}</div>`);m.innerHTML=`${visual}<div class="label">${esc(label)}</div>`;if(markerColor&&/^#[0-9A-Fa-f]{6}$/.test(markerColor)){const lab=m.querySelector('.label');if(lab)lab.style.borderColor=markerColor;const ph=m.querySelector('.photo');if(ph)ph.style.borderColor=markerColor;}markersEl.appendChild(m)}'''
m=once(m,old_add,new_add,'map PNG marker')
old_update="window.updateConvoy=function(raw,id){try{state=typeof raw==='string'?JSON.parse(raw||'{}'):(raw||{});myId=id||'';if(!fitted){fitPoints();fitted=true}render()}catch(e){setStatus('Erreur de données de la carte','warn')}};"
new_update="window.updateConvoy=function(raw,id){try{state=typeof raw==='string'?JSON.parse(raw||'{}'):(raw||{});myId=id||'';if(!fitted){fitPoints();fitted=true;render()}else{renderMarkers()}}catch(e){setStatus('Erreur de données de la carte','warn')}};"
m=once(m,old_update,new_update,'snapshot marker-only render')
old_drag="function begin(ev){if(ev.target.tagName==='BUTTON')return;dragging=true;const q=point(ev);startX=q.x;startY=q.y;startWorld=project(center.lat,center.lon);ev.preventDefault()}\nfunction move(ev){if(!dragging)return;const q=point(ev),dx=q.x-startX,dy=q.y-startY;center=unproject(startWorld.x-dx,startWorld.y-dy);render();ev.preventDefault()}\nfunction end(){dragging=false}"
new_drag="function begin(ev){if(ev.target.tagName==='BUTTON')return;dragging=true;const q=point(ev);startX=q.x;startY=q.y;startWorld=project(center.lat,center.lon);lastDX=0;lastDY=0;ev.preventDefault()}\nfunction move(ev){if(!dragging)return;const q=point(ev);lastDX=q.x-startX;lastDY=q.y-startY;tilesEl.style.transform=`translate(${lastDX}px,${lastDY}px)`;markersEl.style.transform=`translate(${lastDX}px,${lastDY}px)`;ev.preventDefault()}\nfunction end(){if(!dragging)return;dragging=false;center=unproject(startWorld.x-lastDX,startWorld.y-lastDY);tilesEl.style.transform='';markersEl.style.transform='';lastDX=0;lastDY=0;render()}"
m=once(m,old_drag,new_drag,'smooth drag')
map_path.write_text(m)

g=gradle_path.read_text();g=once(g,"versionCode 41","versionCode 42",'versionCode');g=once(g,"versionName '0.3.38'","versionName '0.3.39'",'versionName');gradle_path.write_text(g)
a=api_path.read_text();a=once(a,'ModeConvoi-Android/0.3.38','ModeConvoi-Android/0.3.39','user agent');api_path.write_text(a)

# post-conditions
assert 'Emplacements réservés au futur pack Volkswagen' not in main
assert 'VolkswagenIconPack.items()' in main
assert 'renderMarkers()}}catch' in m
assert "translate(${lastDX}px,${lastDY}px)" in m
assert "versionCode 42" in g and "0.3.39" in g
print('Mode Convoi 0.3.39 migration ready')
