from pathlib import Path

root = Path(__file__).resolve().parents[1]
java = root / "android/app/src/main/java/ch/piiwii/modeconvoi"
main_path = java / "MainActivity.java"
live_path = java / "LiveTalkieManager.java"
api_path = java / "ConvoyApi.java"
gradle_path = root / "android/app/build.gradle"


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly 1 anchor, found {count}")
    return text.replace(old, new, 1)


live = live_path.read_text()

live = replace_once(live,
'''    private int oldAudioMode = AudioManager.MODE_NORMAL;\n    private int oldVoiceVolume = -1;\n    private boolean oldSpeakerphoneOn = false;\n    private AudioDeviceInfo oldCommunicationDevice = null;\n''',
'''    // Audio routing is owned only while Mode Convoi is actually playing/recording talkie audio.\n    // Keeping MODE_IN_COMMUNICATION active while the app is in the background hijacks Android's\n    // volume keys/mixer (for example while watching TikTok), so the previous route is captured\n    // immediately before use and restored as soon as the talkie becomes idle/backgrounded.\n    private int previousAudioMode = AudioManager.MODE_NORMAL;\n    private boolean previousSpeakerphoneOn = false;\n    private AudioDeviceInfo previousCommunicationDevice = null;\n    private volatile boolean audioRouteOwned = false;\n    private volatile boolean hostForeground = true;\n''', 'audio route fields')

live = replace_once(live,
'''    public boolean isRunning() { return running; }\n    public boolean isTransmitting() { return transmitting; }\n\n    public int connectedPeerCount() {\n''',
'''    public boolean isRunning() { return running; }\n    public boolean isTransmitting() { return transmitting; }\n\n    /**\n     * The WebRTC signalling/peer mesh may stay alive in background so we can still identify\n     * who is speaking, but background Mode Convoi must never keep Android's communication\n     * audio route or volume stream captive.\n     */\n    public void setHostForeground(boolean foreground) {\n        hostForeground = foreground;\n        if (!foreground) {\n            transmitting = false;\n            transmittingSince = 0L;\n            micLevel = 0.0;\n            try { if (localAudioTrack != null) localAudioTrack.setEnabled(false); } catch (Throwable ignored) {}\n            muteTalkieOutputAndReleaseRoute();\n        } else if (receivingAudio && receiveEnabled) {\n            ensureReceivePath();\n        } else {\n            muteTalkieOutputAndReleaseRoute();\n        }\n        notifyState(foreground ? stateLabel() : "● Live en arrière-plan");\n    }\n\n    public int connectedPeerCount() {\n''', 'host foreground API')

live = replace_once(live,
'''    public void setReceiveEnabled(boolean enabled) {\n        receiveEnabled = enabled;\n        prefs.putBool("talkieReceive", enabled);\n        try { if (audioDeviceModule != null) audioDeviceModule.setSpeakerMute(!enabled); } catch (Throwable ignored) {}\n        synchronized (peerLock) {\n            for (PeerState p : peers.values()) {\n                try { if (p.remoteTrack != null) p.remoteTrack.setEnabled(enabled); } catch (Throwable ignored) {}\n            }\n        }\n        if (enabled) ensureReceivePath();\n        else { receivingAudio = false; receiveLevel = 0.0; }\n        notifyState(enabled ? stateLabel() : "Réception live coupée");\n    }\n''',
'''    public void setReceiveEnabled(boolean enabled) {\n        receiveEnabled = enabled;\n        prefs.putBool("talkieReceive", enabled);\n        synchronized (peerLock) {\n            for (PeerState p : peers.values()) {\n                try { if (p.remoteTrack != null) p.remoteTrack.setEnabled(enabled); } catch (Throwable ignored) {}\n            }\n        }\n        if (!enabled) {\n            receivingAudio = false;\n            receivingPeerName = "";\n            receiveLevel = 0.0;\n            muteTalkieOutputAndReleaseRoute();\n        } else if (hostForeground && receivingAudio) {\n            ensureReceivePath();\n        } else {\n            // Keep RTP alive for speaker detection, but do not own Android audio while idle/background.\n            muteTalkieOutputAndReleaseRoute();\n        }\n        notifyState(enabled ? stateLabel() : "Réception live coupée");\n    }\n''', 'receive toggle')

live = replace_once(live,
'''    public boolean setTransmitting(boolean enabled) {\n        ensureStarted();\n        if (!running || localAudioTrack == null) return false;\n        transmitting = enabled;\n        transmittingSince = enabled ? System.currentTimeMillis() : 0L;\n        try {\n            routeAudioToSpeaker();\n            localAudioTrack.setEnabled(enabled);\n            ensureLocalSendersAttached();\n            if (enabled) prepareTransmitHealthCheck();\n            else ensureReceivePath();\n        } catch (Throwable t) {\n            lastError = safeMessage(t, "Micro WebRTC indisponible");\n            transmitting = false;\n            notifyState("Micro live indisponible");\n            return false;\n        }\n        if (!enabled) micLevel = 0.0;\n        if (enabled) notifyState(connectedPeerCount() > 0 ? "● EN DIRECT" : "● EN DIRECT · connexion aux autres…");\n        else notifyState(stateLabel());\n        return true;\n    }\n''',
'''    public boolean setTransmitting(boolean enabled) {\n        ensureStarted();\n        if (!running || localAudioTrack == null) return false;\n        if (enabled && !hostForeground) return false;\n        transmitting = enabled;\n        transmittingSince = enabled ? System.currentTimeMillis() : 0L;\n        try {\n            if (enabled) {\n                activateTalkieAudioRoute();\n                try { if (audioDeviceModule != null) audioDeviceModule.setSpeakerMute(true); } catch (Throwable ignored) {}\n            }\n            localAudioTrack.setEnabled(enabled);\n            ensureLocalSendersAttached();\n            if (enabled) prepareTransmitHealthCheck();\n            else if (hostForeground && receiveEnabled && receivingAudio) ensureReceivePath();\n            else muteTalkieOutputAndReleaseRoute();\n        } catch (Throwable t) {\n            lastError = safeMessage(t, "Micro WebRTC indisponible");\n            transmitting = false;\n            muteTalkieOutputAndReleaseRoute();\n            notifyState("Micro live indisponible");\n            return false;\n        }\n        if (!enabled) micLevel = 0.0;\n        if (enabled) notifyState(connectedPeerCount() > 0 ? "● EN DIRECT" : "● EN DIRECT · connexion aux autres…");\n        else notifyState(stateLabel());\n        return true;\n    }\n''', 'push to talk route')

live = replace_once(live,
'''        audioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);\n        if (audioManager != null) {\n            oldAudioMode = audioManager.getMode();\n            try { oldVoiceVolume = audioManager.getStreamVolume(AudioManager.STREAM_VOICE_CALL); } catch (Throwable ignored) {}\n            try { oldSpeakerphoneOn = audioManager.isSpeakerphoneOn(); } catch (Throwable ignored) {}\n            if (Build.VERSION.SDK_INT >= 31) {\n                try { oldCommunicationDevice = audioManager.getCommunicationDevice(); } catch (Throwable ignored) {}\n            }\n            routeAudioToSpeaker();\n        }\n''',
'''        audioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);\n        // Do not switch Android to MODE_IN_COMMUNICATION merely because a convoy session exists.\n        // Routing is activated lazily only for actual foreground talkie audio.\n''', 'init audio route')

live = replace_once(live,
'''        audioDeviceModule.setSpeakerMute(!receiveEnabled);\n''',
'''        // Start muted. Incoming RTP is still measured; output is unmuted only when foreground audio exists.\n        audioDeviceModule.setSpeakerMute(true);\n''', 'initial speaker mute')

live = replace_once(live,
'''        try { if (localAudioTrack != null) localAudioTrack.dispose(); } catch (Throwable ignored) {}\n        try { if (audioSource != null) audioSource.dispose(); } catch (Throwable ignored) {}\n        try { if (factory != null) factory.dispose(); } catch (Throwable ignored) {}\n        try { if (audioDeviceModule != null) audioDeviceModule.release(); } catch (Throwable ignored) {}\n        localAudioTrack = null;\n        audioSource = null;\n        factory = null;\n        audioDeviceModule = null;\n        if (audioManager != null) {\n            if (Build.VERSION.SDK_INT >= 31) {\n                try {\n                    if (oldCommunicationDevice != null) audioManager.setCommunicationDevice(oldCommunicationDevice);\n                    else audioManager.clearCommunicationDevice();\n                } catch (Throwable ignored) {}\n            }\n            try { audioManager.setSpeakerphoneOn(oldSpeakerphoneOn); } catch (Throwable ignored) {}\n            if (oldVoiceVolume >= 0) {\n                try { audioManager.setStreamVolume(AudioManager.STREAM_VOICE_CALL, oldVoiceVolume, 0); } catch (Throwable ignored) {}\n            }\n            try { audioManager.setMode(oldAudioMode); } catch (Throwable ignored) {}\n        }\n        oldCommunicationDevice = null;\n        oldVoiceVolume = -1;\n''',
'''        try { if (audioDeviceModule != null) audioDeviceModule.setSpeakerMute(true); } catch (Throwable ignored) {}\n        restoreSystemAudioRoute();\n        try { if (localAudioTrack != null) localAudioTrack.dispose(); } catch (Throwable ignored) {}\n        try { if (audioSource != null) audioSource.dispose(); } catch (Throwable ignored) {}\n        try { if (factory != null) factory.dispose(); } catch (Throwable ignored) {}\n        try { if (audioDeviceModule != null) audioDeviceModule.release(); } catch (Throwable ignored) {}\n        localAudioTrack = null;\n        audioSource = null;\n        factory = null;\n        audioDeviceModule = null;\n''', 'stop audio restore')

live = replace_once(live,
'''    private void routeAudioToSpeaker() {\n        if (audioManager == null) return;\n        try { audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION); } catch (Throwable ignored) {}\n        if (Build.VERSION.SDK_INT >= 31) {\n            try {\n                AudioDeviceInfo speaker = null;\n                for (AudioDeviceInfo d : audioManager.getAvailableCommunicationDevices()) {\n                    if (d != null && d.getType() == AudioDeviceInfo.TYPE_BUILTIN_SPEAKER) { speaker = d; break; }\n                }\n                if (speaker != null) audioManager.setCommunicationDevice(speaker);\n            } catch (Throwable ignored) {}\n        }\n        try { audioManager.setSpeakerphoneOn(true); } catch (Throwable ignored) {}\n        try {\n            int max = audioManager.getStreamMaxVolume(AudioManager.STREAM_VOICE_CALL);\n            if (max > 0 && !audioManager.isVolumeFixed()) audioManager.setStreamVolume(AudioManager.STREAM_VOICE_CALL, max, 0);\n        } catch (Throwable ignored) {}\n    }\n''',
'''    private synchronized void activateTalkieAudioRoute() {\n        if (audioManager == null || !hostForeground) return;\n        if (!audioRouteOwned) {\n            try { previousAudioMode = audioManager.getMode(); } catch (Throwable ignored) { previousAudioMode = AudioManager.MODE_NORMAL; }\n            try { previousSpeakerphoneOn = audioManager.isSpeakerphoneOn(); } catch (Throwable ignored) { previousSpeakerphoneOn = false; }\n            previousCommunicationDevice = null;\n            if (Build.VERSION.SDK_INT >= 31) {\n                try { previousCommunicationDevice = audioManager.getCommunicationDevice(); } catch (Throwable ignored) {}\n            }\n            audioRouteOwned = true;\n        }\n        try { audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION); } catch (Throwable ignored) {}\n        if (Build.VERSION.SDK_INT >= 31) {\n            try {\n                AudioDeviceInfo speaker = null;\n                for (AudioDeviceInfo d : audioManager.getAvailableCommunicationDevices()) {\n                    if (d != null && d.getType() == AudioDeviceInfo.TYPE_BUILTIN_SPEAKER) { speaker = d; break; }\n                }\n                if (speaker != null) audioManager.setCommunicationDevice(speaker);\n            } catch (Throwable ignored) {}\n        }\n        try { audioManager.setSpeakerphoneOn(true); } catch (Throwable ignored) {}\n        // Never change STREAM_VOICE_CALL volume here: volume belongs to the user/system mixer.\n    }\n\n    private synchronized void restoreSystemAudioRoute() {\n        if (audioManager == null || !audioRouteOwned) return;\n        if (Build.VERSION.SDK_INT >= 31) {\n            try {\n                if (previousCommunicationDevice != null) audioManager.setCommunicationDevice(previousCommunicationDevice);\n                else audioManager.clearCommunicationDevice();\n            } catch (Throwable ignored) {}\n        }\n        try { audioManager.setSpeakerphoneOn(previousSpeakerphoneOn); } catch (Throwable ignored) {}\n        try { audioManager.setMode(previousAudioMode); } catch (Throwable ignored) {}\n        previousCommunicationDevice = null;\n        audioRouteOwned = false;\n    }\n\n    private void muteTalkieOutputAndReleaseRoute() {\n        try { if (audioDeviceModule != null) audioDeviceModule.setSpeakerMute(true); } catch (Throwable ignored) {}\n        restoreSystemAudioRoute();\n    }\n''', 'routing implementation')

live = replace_once(live,
'''        if (list.isEmpty()) {\n            receivingAudio = false;\n            receivingPeerName = "";\n            receiveLevel = 0.0;\n            micLevel = 0.0;\n            notifyState(stateLabel());\n            scheduleAudioMeter(350);\n            return;\n        }\n''',
'''        if (list.isEmpty()) {\n            receivingAudio = false;\n            receivingPeerName = "";\n            receiveLevel = 0.0;\n            micLevel = 0.0;\n            if (!transmitting) muteTalkieOutputAndReleaseRoute();\n            notifyState(stateLabel());\n            scheduleAudioMeter(350);\n            return;\n        }\n''', 'idle meter route release')

live = replace_once(live,
'''                        receivingAudio = receiveEnabled && !transmitting && receiveLevel >= 0.012;\n                        if (receivingAudio && loudest[0] != null) {\n                            String n = loudest[0].displayName == null ? "" : loudest[0].displayName.trim();\n                            receivingPeerName = n.isEmpty() ? "Un participant" : n;\n                        } else receivingPeerName = "";\n                        if (receivingAudio) ensureReceivePath();\n                        notifyState(stateLabel());\n''',
'''                        boolean wasReceiving = receivingAudio;\n                        receivingAudio = receiveEnabled && !transmitting && receiveLevel >= 0.012;\n                        if (receivingAudio && loudest[0] != null) {\n                            String n = loudest[0].displayName == null ? "" : loudest[0].displayName.trim();\n                            receivingPeerName = n.isEmpty() ? "Un participant" : n;\n                        } else receivingPeerName = "";\n                        if (receivingAudio && hostForeground) ensureReceivePath();\n                        else if (!transmitting && (wasReceiving || !hostForeground)) muteTalkieOutputAndReleaseRoute();\n                        notifyState(stateLabel());\n''', 'speaker detection routing')

live = replace_once(live,
'''    private void ensureReceivePath() {\n        if (!receiveEnabled) return;\n        try { if (audioDeviceModule != null) audioDeviceModule.setSpeakerMute(false); } catch (Throwable ignored) {}\n        synchronized (peerLock) {\n            for (PeerState state : peers.values()) {\n                try { if (state.remoteTrack != null) state.remoteTrack.setEnabled(true); } catch (Throwable ignored) {}\n            }\n        }\n        routeAudioToSpeaker();\n    }\n''',
'''    private void ensureReceivePath() {\n        if (!receiveEnabled || !hostForeground) {\n            muteTalkieOutputAndReleaseRoute();\n            return;\n        }\n        activateTalkieAudioRoute();\n        try { if (audioDeviceModule != null) audioDeviceModule.setSpeakerMute(false); } catch (Throwable ignored) {}\n        synchronized (peerLock) {\n            for (PeerState state : peers.values()) {\n                try { if (state.remoteTrack != null) state.remoteTrack.setEnabled(true); } catch (Throwable ignored) {}\n            }\n        }\n    }\n''', 'receive route')

if 'oldVoiceVolume' in live or 'routeAudioToSpeaker()' in live:
    raise SystemExit('obsolete permanent audio routing remains')
if 'setStreamVolume(AudioManager.STREAM_VOICE_CALL' in live:
    raise SystemExit('voice-call volume forcing remains')
if 'setHostForeground' not in live or 'muteTalkieOutputAndReleaseRoute' not in live:
    raise SystemExit('new audio ownership lifecycle missing')
live_path.write_text(live)

main = main_path.read_text()
main = replace_once(main,
'''    @Override protected void onResume() { super.onResume(); activityForeground=true; NotificationHelper.clearTalkieSpeaker(this); if(visualAlertController!=null)ConvoyForegroundAlertBus.register(visualAlertController); if (prefs.hasActiveConvoy()) { startPolling(); startShareServiceIfPermitted(); if(liveTalkie!=null)liveTalkie.ensureStarted(); } }\n    @Override protected void onPause() { activityForeground=false; if(visualAlertController!=null)ConvoyForegroundAlertBus.unregister(visualAlertController); super.onPause(); stopPolling(); }\n''',
'''    @Override protected void onResume() { super.onResume(); activityForeground=true; if(liveTalkie!=null)liveTalkie.setHostForeground(true); NotificationHelper.clearTalkieSpeaker(this); if(visualAlertController!=null)ConvoyForegroundAlertBus.register(visualAlertController); if (prefs.hasActiveConvoy()) { startPolling(); startShareServiceIfPermitted(); if(liveTalkie!=null)liveTalkie.ensureStarted(); } }\n    @Override protected void onPause() { activityForeground=false; if(liveTalkie!=null)liveTalkie.setHostForeground(false); if(visualAlertController!=null)ConvoyForegroundAlertBus.unregister(visualAlertController); super.onPause(); stopPolling(); }\n''', 'activity audio lifecycle')
main = main.replace('0.3.37', '0.3.38')
main_path.write_text(main)

api = api_path.read_text()
api = replace_once(api, 'ModeConvoi-Android/0.3.37', 'ModeConvoi-Android/0.3.38', 'user agent')
api_path.write_text(api)

gradle = gradle_path.read_text()
gradle = replace_once(gradle, 'versionCode 40', 'versionCode 41', 'version code')
gradle = replace_once(gradle, "versionName '0.3.37'", "versionName '0.3.38'", 'version name')
gradle_path.write_text(gradle)

print('Mode Convoi 0.3.38 audio ownership patch applied')
