from pathlib import Path

root = Path(__file__).resolve().parents[1]
live_path = root / "android/app/src/main/java/ch/piiwii/modeconvoi/LiveTalkieManager.java"


def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly 1 anchor, found {count}")
    return text.replace(old, new, 1)


live = live_path.read_text()

live = replace_once(live,
'''    private final Map<String, PeerState> peers = new HashMap<>();\n    private final Map<String, Long> lastRepairByPeer = new HashMap<>();\n''',
'''    private final Map<String, PeerState> peers = new HashMap<>();\n    private final Map<String, String> participantNames = new HashMap<>();\n    private final Map<String, Long> lastRepairByPeer = new HashMap<>();\n''', 'participant name cache')

live = replace_once(live,
'''    private volatile boolean hostForeground = true;\n\n    private volatile boolean running = false;\n''',
'''    private volatile boolean hostForeground = true;\n    private volatile boolean backgroundSignalingOnly = false;\n\n    private volatile boolean running = false;\n''', 'background signalling state')

live = replace_once(live,
'''    private volatile boolean receivingAudio = false;\n    private volatile String receivingPeerName = "";\n    private volatile double receiveLevel = 0.0;\n''',
'''    private volatile boolean receivingAudio = false;\n    private volatile String receivingPeerName = "";\n    private volatile String receivingPeerId = "";\n    private volatile long lastRemoteTalkSignalAt = 0L;\n    private volatile long lastTalkBroadcastAt = 0L;\n    private volatile double receiveLevel = 0.0;\n''', 'talk activity state')

live = replace_once(live,
'''        String key = prefs.get("code", "") + ":" + prefs.get("participantId", "");\n        if (running && key.equals(sessionKey)) return;\n        stopSession();\n        try {\n            initWebRtc();\n            sessionKey = key;\n            lastSignalId = prefs.getLong("liveSignalLastId", 0);\n            running = true;\n            lastError = "";\n            scheduleSignalPoll(0);\n            scheduleAudioMeter(250);\n            notifyState("Connexion live…");\n        } catch (Throwable t) {\n            lastError = safeMessage(t, "Initialisation WebRTC impossible");\n            notifyState("Live indisponible : " + lastError);\n        }\n''',
'''        String key = prefs.get("code", "") + ":" + prefs.get("participantId", "");\n        if (running && key.equals(sessionKey)) {\n            if (hostForeground && backgroundSignalingOnly) resumeWebRtcForeground();\n            return;\n        }\n        stopSession();\n        try {\n            sessionKey = key;\n            lastSignalId = prefs.getLong("liveSignalLastId", 0);\n            running = true;\n            lastError = "";\n            backgroundSignalingOnly = !hostForeground;\n            if (hostForeground) initWebRtc();\n            scheduleSignalPoll(0);\n            if (hostForeground) scheduleAudioMeter(250);\n            notifyState(hostForeground ? "Connexion live…" : "● Live en arrière-plan");\n        } catch (Throwable t) {\n            lastError = safeMessage(t, "Initialisation WebRTC impossible");\n            running = false;\n            backgroundSignalingOnly = false;\n            notifyState("Live indisponible : " + lastError);\n        }\n''', 'session start background safety')

live = replace_once(live,
'''    public void setHostForeground(boolean foreground) {\n        hostForeground = foreground;\n        if (!foreground) {\n            transmitting = false;\n            transmittingSince = 0L;\n            micLevel = 0.0;\n            try { if (localAudioTrack != null) localAudioTrack.setEnabled(false); } catch (Throwable ignored) {}\n            muteTalkieOutputAndReleaseRoute();\n        } else if (receivingAudio && receiveEnabled) {\n            ensureReceivePath();\n        } else {\n            muteTalkieOutputAndReleaseRoute();\n        }\n        notifyState(foreground ? stateLabel() : "● Live en arrière-plan");\n    }\n''',
'''    public void setHostForeground(boolean foreground) {\n        if (hostForeground == foreground && !(foreground && backgroundSignalingOnly)) return;\n        if (!foreground && transmitting) broadcastTalkState(false);\n        hostForeground = foreground;\n        if (!foreground) {\n            transmitting = false;\n            transmittingSince = 0L;\n            micLevel = 0.0;\n            try { if (localAudioTrack != null) localAudioTrack.setEnabled(false); } catch (Throwable ignored) {}\n            if (running) suspendWebRtcForBackground();\n            else muteTalkieOutputAndReleaseRoute();\n            notifyState("● Live en arrière-plan");\n        } else {\n            if (running && backgroundSignalingOnly) resumeWebRtcForeground();\n            else if (receivingAudio && receiveEnabled) ensureReceivePath();\n            else muteTalkieOutputAndReleaseRoute();\n            notifyState(stateLabel());\n        }\n    }\n''', 'foreground transition')

live = replace_once(live,
'''        if (!running || localAudioTrack == null) return false;\n        if (enabled && !hostForeground) return false;\n        transmitting = enabled;\n        transmittingSince = enabled ? System.currentTimeMillis() : 0L;\n''',
'''        if (!running || localAudioTrack == null || backgroundSignalingOnly) return false;\n        if (enabled && !hostForeground) return false;\n        boolean changed = transmitting != enabled;\n        transmitting = enabled;\n        transmittingSince = enabled ? System.currentTimeMillis() : 0L;\n''', 'ptt transition state')

live = replace_once(live,
'''        if (!enabled) micLevel = 0.0;\n        if (enabled) notifyState(connectedPeerCount() > 0 ? "● EN DIRECT" : "● EN DIRECT · connexion aux autres…");\n        else notifyState(stateLabel());\n        return true;\n''',
'''        if (!enabled) micLevel = 0.0;\n        if (changed) {\n            broadcastTalkState(enabled);\n            lastTalkBroadcastAt = enabled ? System.currentTimeMillis() : 0L;\n        }\n        if (enabled) notifyState(connectedPeerCount() > 0 ? "● EN DIRECT" : "● EN DIRECT · connexion aux autres…");\n        else notifyState(stateLabel());\n        return true;\n''', 'ptt signal broadcast')

live = replace_once(live,
'''        receivingAudio = false;\n        receivingPeerName = "";\n        receiveLevel = 0.0;\n        micLevel = 0.0;\n''',
'''        receivingAudio = false;\n        receivingPeerName = "";\n        receivingPeerId = "";\n        lastRemoteTalkSignalAt = 0L;\n        lastTalkBroadcastAt = 0L;\n        receiveLevel = 0.0;\n        micLevel = 0.0;\n''', 'stop talk activity')

live = replace_once(live,
'''            peers.clear();\n            lastRepairByPeer.clear();\n        }\n''',
'''            peers.clear();\n            participantNames.clear();\n            lastRepairByPeer.clear();\n        }\n''', 'stop participant cache')

live = replace_once(live,
'''        sessionKey = "";\n        lastSignalId = 0;\n    }\n\n    private synchronized void activateTalkieAudioRoute() {\n''',
'''        sessionKey = "";\n        lastSignalId = 0;\n        backgroundSignalingOnly = false;\n    }\n\n    private void suspendWebRtcForBackground() {\n        backgroundSignalingOnly = true;\n        meterScheduled = false;\n        receivingAudio = false;\n        receivingPeerName = "";\n        receivingPeerId = "";\n        receiveLevel = 0.0;\n        micLevel = 0.0;\n        synchronized (peerLock) {\n            for (PeerState p : peers.values()) closePeerInternal(p);\n            peers.clear();\n            lastRepairByPeer.clear();\n        }\n        try { if (audioDeviceModule != null) audioDeviceModule.setSpeakerMute(true); } catch (Throwable ignored) {}\n        restoreSystemAudioRoute();\n        try { if (localAudioTrack != null) localAudioTrack.dispose(); } catch (Throwable ignored) {}\n        try { if (audioSource != null) audioSource.dispose(); } catch (Throwable ignored) {}\n        try { if (factory != null) factory.dispose(); } catch (Throwable ignored) {}\n        try { if (audioDeviceModule != null) audioDeviceModule.release(); } catch (Throwable ignored) {}\n        localAudioTrack = null;\n        audioSource = null;\n        factory = null;\n        audioDeviceModule = null;\n        // Signal polling stays alive: it receives ptt-start/ptt-stop without owning any Android audio device.\n        scheduleSignalPoll(0);\n    }\n\n    private void resumeWebRtcForeground() {\n        if (!running || !hostForeground || !backgroundSignalingOnly) return;\n        try {\n            initWebRtc();\n            backgroundSignalingOnly = false;\n            lastError = "";\n            scheduleAudioMeter(120);\n            scheduleSignalPoll(0);\n            notifyState("◌ Reconnexion live…");\n        } catch (Throwable t) {\n            lastError = safeMessage(t, "Réactivation WebRTC impossible");\n            suspendWebRtcForBackground();\n            notifyState("⚠ " + lastError);\n        }\n    }\n\n    private synchronized void activateTalkieAudioRoute() {\n''', 'background WebRTC suspension helpers')

live = replace_once(live,
'''    private void pollAudioMeters() {\n        if (!running) return;\n''',
'''    private void pollAudioMeters() {\n        if (!running || backgroundSignalingOnly) return;\n''', 'disable audio meter in background')

live = replace_once(live,
'''                        if (receivingAudio && loudest[0] != null) {\n                            String n = loudest[0].displayName == null ? "" : loudest[0].displayName.trim();\n                            receivingPeerName = n.isEmpty() ? "Un participant" : n;\n                        } else receivingPeerName = "";\n                        if (receivingAudio && hostForeground) ensureReceivePath();\n                        else if (!transmitting && (wasReceiving || !hostForeground)) muteTalkieOutputAndReleaseRoute();\n                        notifyState(stateLabel());\n''',
'''                        if (receivingAudio && loudest[0] != null) {\n                            String n = loudest[0].displayName == null ? "" : loudest[0].displayName.trim();\n                            receivingPeerName = n.isEmpty() ? "Un participant" : n;\n                            receivingPeerId = loudest[0].peerId;\n                        } else { receivingPeerName = ""; receivingPeerId = ""; }\n                        if (transmitting && System.currentTimeMillis() - lastTalkBroadcastAt >= 900L) {\n                            broadcastTalkState(true);\n                            lastTalkBroadcastAt = System.currentTimeMillis();\n                        }\n                        if (receivingAudio && hostForeground) ensureReceivePath();\n                        else if (!transmitting && (wasReceiving || !hostForeground)) muteTalkieOutputAndReleaseRoute();\n                        notifyState(stateLabel());\n''', 'audio meter speaker/heartbeat')

live = replace_once(live,
'''            lastError = "";\n            notifyState(stateLabel());\n            scheduleSignalPoll(allPeersConnected() ? 1400 : 550);\n''',
'''            if (backgroundSignalingOnly && receivingAudio && lastRemoteTalkSignalAt > 0\n                    && System.currentTimeMillis() - lastRemoteTalkSignalAt > 2600L) {\n                receivingAudio = false;\n                receivingPeerName = "";\n                receivingPeerId = "";\n            }\n            lastError = "";\n            notifyState(stateLabel());\n            scheduleSignalPoll(backgroundSignalingOnly ? 700 : (allPeersConnected() ? 1400 : 550));\n''', 'background signal cadence/timeout')

old_sync = '''    private void syncPeersFromParticipants(JSONArray participants, String me) {\n        if (participants == null) return;\n        Set<String> seen = new HashSet<>();\n        long now = System.currentTimeMillis();\n        for (int i = 0; i < participants.length(); i++) {\n            JSONObject p = participants.optJSONObject(i);\n            if (p == null) continue;\n            String id = p.optString("id", "");\n            if (id.isEmpty() || id.equals(me)) continue;\n            long lastSeen = p.optLong("lastSeen", now);\n            // Do not keep creating WebRTC sessions for phones that have been absent for several minutes.\n            if (lastSeen > 0 && now - lastSeen > 180_000L) continue;\n            seen.add(id);\n            String displayName = p.optString("name", "").trim();\n            PeerState ps;\n            synchronized (peerLock) { ps = peers.get(id); }\n            if (ps == null) ps = createPeer(id);\n            if (ps != null && !displayName.isEmpty()) ps.displayName = displayName;\n        }\n        List<String> remove = new ArrayList<>();\n        synchronized (peerLock) {\n            for (String id : peers.keySet()) if (!seen.contains(id)) remove.add(id);\n        }\n        for (String id : remove) removePeer(id);\n    }\n'''
new_sync = '''    private void syncPeersFromParticipants(JSONArray participants, String me) {\n        if (participants == null) return;\n        Set<String> seen = new HashSet<>();\n        long now = System.currentTimeMillis();\n        for (int i = 0; i < participants.length(); i++) {\n            JSONObject p = participants.optJSONObject(i);\n            if (p == null) continue;\n            String id = p.optString("id", "");\n            if (id.isEmpty() || id.equals(me)) continue;\n            long lastSeen = p.optLong("lastSeen", now);\n            if (lastSeen > 0 && now - lastSeen > 180_000L) continue;\n            seen.add(id);\n            String displayName = p.optString("name", "").trim();\n            synchronized (peerLock) {\n                if (!displayName.isEmpty()) participantNames.put(id, displayName);\n                else if (!participantNames.containsKey(id)) participantNames.put(id, "Un participant");\n            }\n            if (backgroundSignalingOnly || !hostForeground || factory == null || localAudioTrack == null) continue;\n            PeerState ps;\n            synchronized (peerLock) { ps = peers.get(id); }\n            if (ps == null) ps = createPeer(id);\n            if (ps != null && !displayName.isEmpty()) ps.displayName = displayName;\n        }\n        List<String> remove = new ArrayList<>();\n        synchronized (peerLock) {\n            for (String id : peers.keySet()) if (!seen.contains(id)) remove.add(id);\n            participantNames.keySet().removeIf(id -> !seen.contains(id));\n        }\n        for (String id : remove) removePeer(id);\n    }\n'''
live = replace_once(live, old_sync, new_sync, 'background participant sync')

live = replace_once(live,
'''        String payload = m.optString("payload", "");\n        if (from.isEmpty() || from.equals(prefs.get("participantId", ""))) return;\n        PeerState state;\n        synchronized (peerLock) { state = peers.get(from); }\n        if (state == null) state = createPeer(from);\n        if (state == null || !isCurrent(state)) return;\n\n        if ("offer".equals(type)) {\n''',
'''        String payload = m.optString("payload", "");\n        if (from.isEmpty() || from.equals(prefs.get("participantId", ""))) return;\n\n        if ("ptt-start".equals(type)) {\n            if (!receiveEnabled) return;\n            String who = payload == null ? "" : payload.trim();\n            if (who.isEmpty()) { synchronized (peerLock) { who = participantNames.get(from); } }\n            receivingPeerId = from;\n            receivingPeerName = who == null || who.trim().isEmpty() ? "Un participant" : who.trim();\n            receivingAudio = true;\n            lastRemoteTalkSignalAt = System.currentTimeMillis();\n            notifyState(stateLabel());\n            return;\n        } else if ("ptt-stop".equals(type)) {\n            if (from.equals(receivingPeerId)) {\n                receivingAudio = false;\n                receivingPeerName = "";\n                receivingPeerId = "";\n                lastRemoteTalkSignalAt = 0L;\n                notifyState(stateLabel());\n            }\n            return;\n        }\n\n        // In background we intentionally do not create any PeerConnection/ADM. Old SDP/ICE is\n        // consumed and discarded; a fresh deterministic negotiation is started on foreground resume.\n        if (backgroundSignalingOnly || !hostForeground || factory == null || localAudioTrack == null) return;\n        PeerState state;\n        synchronized (peerLock) { state = peers.get(from); }\n        if (state == null) state = createPeer(from);\n        if (state == null || !isCurrent(state)) return;\n\n        if ("offer".equals(type)) {\n''', 'ptt signal handling before WebRTC')

live = replace_once(live,
'''    private void sendSignal(String to, String type, String payload) {\n''',
'''    private void broadcastTalkState(boolean active) {\n        if (!running || !prefs.hasActiveConvoy()) return;\n        Set<String> ids = new HashSet<>();\n        synchronized (peerLock) {\n            ids.addAll(participantNames.keySet());\n            ids.addAll(peers.keySet());\n        }\n        String me = prefs.get("participantId", "");\n        String name = prefs.get("profileName", "").trim();\n        if (name.isEmpty()) name = "Un participant";\n        for (String id : ids) {\n            if (id == null || id.isEmpty() || id.equals(me)) continue;\n            sendSignal(id, active ? "ptt-start" : "ptt-stop", active ? name : "");\n        }\n    }\n\n    private void sendSignal(String to, String type, String payload) {\n''', 'talk state broadcaster')

if 'backgroundSignalingOnly' not in live or 'ptt-start' not in live or 'suspendWebRtcForBackground' not in live:
    raise SystemExit('background signalling-only architecture missing')
if 'setStreamVolume(AudioManager.STREAM_VOICE_CALL' in live:
    raise SystemExit('voice call volume forcing returned')

live_path.write_text(live)
print('Mode Convoi 0.3.38 background signalling-only audio isolation applied')
