plugins {
    id 'com.android.application'
}

android {
    namespace 'ch.piiwii.gtigps'
    compileSdk 35

    defaultConfig {
        applicationId 'ch.piiwii.gtigps'
        minSdk 23
        targetSdk 28
        versionCode 6
        versionName '2.1.0'
    }

    lint {
        disable 'ExpiredTargetSdkVersion', 'BlockedPrivateApi'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
