from pathlib import Path
root=Path('build-piiwii-documents-0150/work')
services=root/'src/PiiWii.Documents/Services'

# Version bump.
for rel in ['src/PiiWii.Documents/PiiWii.Documents.csproj','src/PiiWii.Documents.Installer/PiiWii.Documents.Installer.csproj','src/PiiWii.Documents.Installer/Program.cs','src/PiiWii.Documents/Services/BridgeService.cs','src/PiiWii.Documents/Services/AssistantExchangeService.cs','src/PiiWii.Documents/Services/BackupService.cs']:
    p=root/rel
    if p.exists(): p.write_text(p.read_text().replace('0.14.0.0','0.15.0.0').replace('0.14.0','0.15.0'))

# Backup restore: validate manifest + SQLite integrity before replacing the live DB.
p=services/'BackupService.cs';s=p.read_text()
insert='''\n    public sealed record BackupInfo(string Path,DateTime Created,long Size,string Reason);\n    public static List<BackupInfo> ListBackups()\n    {\n        Directory.CreateDirectory(AppPaths.BackupsRoot);\n        return Directory.EnumerateFiles(AppPaths.BackupsRoot,"PiiWii-Documents-*.zip").Select(x=>new FileInfo(x)).OrderByDescending(x=>x.LastWriteTimeUtc).Select(f=>new BackupInfo(f.FullName,f.LastWriteTime,f.Length,Path.GetFileNameWithoutExtension(f.Name))).ToList();\n    }\n\n    public static string ValidateBackup(string zipPath)\n    {\n        if(!File.Exists(zipPath)) throw new FileNotFoundException("Sauvegarde introuvable.",zipPath);\n        var tmp=Path.Combine(Path.GetTempPath(),$"piiwii-validate-{Guid.NewGuid():N}");Directory.CreateDirectory(tmp);\n        try\n        {\n            using var z=ZipFile.OpenRead(zipPath);\n            var me=z.GetEntry("manifest.json")??throw new InvalidDataException("manifest.json absent.");\n            using var ms=me.Open();using var sr=new StreamReader(ms);using var jd=JsonDocument.Parse(sr.ReadToEnd());\n            if(!jd.RootElement.TryGetProperty("schema",out var sc)||sc.GetString()!="piiwii-documents-backup-v1")throw new InvalidDataException("Format de sauvegarde non reconnu.");\n            var de=z.GetEntry("piiwii-documents.db")??throw new InvalidDataException("Base SQLite absente.");\n            var db=Path.Combine(tmp,"piiwii-documents.db");de.ExtractToFile(db,true);\n            using var cn=new SqliteConnection($"Data Source={db};Mode=ReadOnly");cn.Open();using var cmd=cn.CreateCommand();cmd.CommandText="PRAGMA integrity_check;";var r=cmd.ExecuteScalar()?.ToString()??"";if(!string.Equals(r,"ok",StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("La sauvegarde SQLite est endommagée : "+r);\n            return jd.RootElement.TryGetProperty("createdAt",out var ca)?$"Sauvegarde valide — créée le {ca.GetDateTime().ToLocalTime():dd.MM.yyyy HH:mm}":"Sauvegarde valide";\n        }\n        finally{try{Directory.Delete(tmp,true);}catch{}}\n    }\n\n    public static void RestoreDatabaseBackup(string zipPath)\n    {\n        ValidateBackup(zipPath);\n        CreateDatabaseBackup("avant-restauration",true);\n        var tmp=Path.Combine(Path.GetTempPath(),$"piiwii-restore-{Guid.NewGuid():N}");Directory.CreateDirectory(tmp);\n        try\n        {\n            using(var z=ZipFile.OpenRead(zipPath)){var de=z.GetEntry("piiwii-documents.db")??throw new InvalidDataException("Base SQLite absente.");de.ExtractToFile(Path.Combine(tmp,"piiwii-documents.db"),true);}\n            try{File.Delete(AppPaths.DatabasePath+"-wal");}catch{} try{File.Delete(AppPaths.DatabasePath+"-shm");}catch{}\n            File.Copy(Path.Combine(tmp,"piiwii-documents.db"),AppPaths.DatabasePath,true);\n        }\n        finally{try{Directory.Delete(tmp,true);}catch{}}\n    }\n'''
if 'public sealed record BackupInfo' not in s:
    pos=s.rfind('\n}')
    s=s[:pos]+insert+s[pos:]
p.write_text(s)

# Bridge: expose safe local session inventory + selective revocation by SQLite rowid.
p=services/'BridgeService.cs';s=p.read_text()
insert='''\n    public sealed record SessionInfo(long Id,string Permissions,string ScopeType,string ScopeValue,DateTime ExpiresAt,DateTime CreatedAt,bool Revoked);\n    public List<SessionInfo> ListSessions()\n    {\n        var list=new List<SessionInfo>();try{using var cn=new SqliteConnection($"Data Source={AppPaths.DatabasePath}");cn.Open();var cmd=cn.CreateCommand();cmd.CommandText="SELECT rowid,permissions,scope_type,scope_value,expires_at,created_at,revoked FROM bridge_tokens ORDER BY created_at DESC LIMIT 50";using var r=cmd.ExecuteReader();while(r.Read())list.Add(new SessionInfo(r.GetInt64(0),r.GetString(1),r[2]?.ToString()??"all",r[3]?.ToString()??"",DateTime.Parse(r.GetString(4)).ToLocalTime(),DateTime.Parse(r.GetString(5)).ToLocalTime(),r.GetInt32(6)!=0));}catch{}return list;\n    }\n    public bool RevokeSession(long id){try{using var cn=new SqliteConnection($"Data Source={AppPaths.DatabasePath}");cn.Open();var cmd=cn.CreateCommand();cmd.CommandText="UPDATE bridge_tokens SET revoked=1 WHERE rowid=$id";cmd.Parameters.AddWithValue("$id",id);var ok=cmd.ExecuteNonQuery()>0;if(ok)DatabaseService.AuditExternal("Utilisateur","Accès pont révoqué",null,$"session={id}");return ok;}catch{return false;}}\n'''
if 'public sealed record SessionInfo' not in s:
    marker='    private async Task Loop(CancellationToken ct)'
    s=s.replace(marker,insert+'\n'+marker)
p.write_text(s)

# ChatGPT package preflight and anti zip-bomb limits.
p=services/'AssistantImportPackService.cs';s=p.read_text()
insert='''\n    public sealed record Inspection(int Documents,int Duplicates,int InvalidHashes,long UncompressedBytes,List<string> Errors);\n    public static Inspection Inspect(string zipPath)\n    {\n        const int maxDocs=500; const long maxEntry=100L*1024*1024; const long maxTotal=2L*1024*1024*1024;\n        var errors=new List<string>();int duplicates=0,bad=0;long total=0;using var z=ZipFile.OpenRead(zipPath);\n        foreach(var e in z.Entries){total+=e.Length;if(e.Length>maxEntry)errors.Add($"Fichier trop volumineux : {e.FullName}");if(total>maxTotal)throw new InvalidDataException("Paquet trop volumineux (maximum 2 Go décompressés).");}\n        var me=z.GetEntry("manifest.json")??throw new InvalidDataException("manifest.json absent du paquet.");using var sr=new StreamReader(me.Open());using var jd=JsonDocument.Parse(sr.ReadToEnd());var root=jd.RootElement;if(root.GetProperty("schema").GetString()!="piiwii-documents-import-v1")throw new InvalidDataException("Format de paquet non reconnu.");var docs=root.GetProperty("documents").EnumerateArray().ToList();if(docs.Count>maxDocs)throw new InvalidDataException($"Trop de documents dans le paquet ({docs.Count}, maximum {maxDocs}).");\n        foreach(var item in docs)try{var rel=item.GetProperty("file").GetString()??"";if(string.IsNullOrWhiteSpace(rel)||rel.Contains("..")){errors.Add($"Chemin interdit : {rel}");continue;}var e=z.GetEntry(rel.Replace('\\\\','/'));if(e==null){errors.Add($"Fichier absent : {rel}");continue;}using var es=e.Open();var sha=Convert.ToHexString(SHA256.HashData(es)).ToLowerInvariant();if(item.TryGetProperty("sha256",out var sh)&&sh.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(sh.GetString())&&!string.Equals(sh.GetString(),sha,StringComparison.OrdinalIgnoreCase)){bad++;errors.Add($"SHA-256 invalide : {rel}");}if(DatabaseService.ShaExists(sha))duplicates++;}catch(Exception ex){errors.Add(ex.Message);}\n        return new(docs.Count,duplicates,bad,total,errors);\n    }\n'''
if 'public sealed record Inspection' not in s:
    marker='    public static async Task<Result> ImportAsync'
    s=s.replace(marker,insert+'\n    public static async Task<Result> ImportAsync')
# Enforce limits during extraction too.
s=s.replace('using(var z=ZipFile.OpenRead(zipPath))foreach(var e in z.Entries){', 'using(var z=ZipFile.OpenRead(zipPath)){long totalUncompressed=0;foreach(var e in z.Entries){totalUncompressed+=e.Length;if(e.Length>100L*1024*1024||totalUncompressed>2L*1024*1024*1024)throw new InvalidDataException("Paquet trop volumineux.");')
s=s.replace('Directory.CreateDirectory(Path.GetDirectoryName(full)!);e.ExtractToFile(full,true);}\n            var manifest=', 'Directory.CreateDirectory(Path.GetDirectoryName(full)!);e.ExtractToFile(full,true);}}\n            var manifest=')
p.write_text(s)

# UI: restore backups, inspect package before import, inspect bridge sessions.
p=root/'src/PiiWii.Documents/MainForm.cs';s=p.read_text().replace('PiiWii Documents 0.14.0','PiiWii Documents 0.15.0').replace('v0.14.0','v0.15.0')
s=s.replace('moreMenu.Items.Add("Révoquer les accès du pont",null,(_,_)=>RevokeBridge());','moreMenu.Items.Add("Voir les accès du pont",null,(_,_)=>ShowBridgeSessions());\n        moreMenu.Items.Add("Révoquer les accès du pont",null,(_,_)=>RevokeBridge());')
s=s.replace('moreMenu.Items.Add("Ouvrir les sauvegardes",null,(_,_)=>Process.Start(new ProcessStartInfo(AppPaths.BackupsRoot){UseShellExecute=true}));','moreMenu.Items.Add("Ouvrir les sauvegardes",null,(_,_)=>Process.Start(new ProcessStartInfo(AppPaths.BackupsRoot){UseShellExecute=true}));\n        moreMenu.Items.Add("Restaurer une sauvegarde",null,(_,_)=>RestoreBackup());')
old='try{var r=await AssistantImportPackService.ImportAsync(o.FileName,pr);lastBatchId=r.BatchId;'
new='try{var check=AssistantImportPackService.Inspect(o.FileName);var mb=check.UncompressedBytes/1024d/1024d;var issues=check.Errors.Count==0?"Aucune anomalie détectée.":string.Join("\\n",check.Errors.Take(8));if(check.InvalidHashes>0){MessageBox.Show($"Import refusé : {check.InvalidHashes} empreinte(s) SHA-256 invalide(s).\\n\\n{issues}","Contrôle du paquet ChatGPT",MessageBoxButtons.OK,MessageBoxIcon.Error);return;}if(MessageBox.Show($"Documents annoncés : {check.Documents}\\nDoublons déjà présents : {check.Duplicates}\\nTaille décompressée : {mb:0.0} Mo\\nAnomalies : {check.Errors.Count}\\n\\n{issues}\\n\\nImporter ce paquet ?","Contrôle du paquet ChatGPT",MessageBoxButtons.YesNo,check.Errors.Count>0?MessageBoxIcon.Warning:MessageBoxIcon.Question)!=DialogResult.Yes)return;var r=await AssistantImportPackService.ImportAsync(o.FileName,pr);lastBatchId=r.BatchId;'
s=s.replace(old,new)
marker='    void RevokeBridge(){var n=BridgeService.Instance.RevokeAll();MessageBox.Show($"{n} session(s) révoquée(s).","Pont sécurisé",MessageBoxButtons.OK,MessageBoxIcon.Information);}'
extra='''    void ShowBridgeSessions(){var list=BridgeService.Instance.ListSessions();if(list.Count==0){MessageBox.Show("Aucune session du pont enregistrée.","Accès du pont",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}var lines=list.Take(20).Select(x=>$"#{x.Id}  {(x.Revoked?"RÉVOQUÉ":x.ExpiresAt<=DateTime.Now?"EXPIRÉ":"ACTIF")}  {x.ScopeType}:{x.ScopeValue}  expire {x.ExpiresAt:dd.MM HH:mm}");MessageBox.Show(string.Join("\\n",lines),"Accès du pont",MessageBoxButtons.OK,MessageBoxIcon.Information);}\n    void RestoreBackup(){using var o=new OpenFileDialog{InitialDirectory=AppPaths.BackupsRoot,Filter="Sauvegarde PiiWii Documents|PiiWii-Documents-*.zip|Fichier ZIP|*.zip",Title="Restaurer une sauvegarde"};if(o.ShowDialog()!=DialogResult.OK)return;try{var check=BackupService.ValidateBackup(o.FileName);if(MessageBox.Show($"{check}\\n\\nLa base actuelle sera sauvegardée avant restauration.\\nRestaurer cette sauvegarde ?","Restaurer",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;BridgeService.Instance.Stop();BackupService.RestoreDatabaseBackup(o.FileName);DatabaseService.Initialize();BridgeService.Instance.Start();RefreshList();LoadSelected();MessageBox.Show("Sauvegarde restaurée. La base a été contrôlée avant remplacement.","Restauration terminée",MessageBoxButtons.OK,MessageBoxIcon.Information);}catch(Exception ex){try{BridgeService.Instance.Start();}catch{}MessageBox.Show(ex.Message,"Restauration impossible",MessageBoxButtons.OK,MessageBoxIcon.Error);}}\n'''
if 'void ShowBridgeSessions()' not in s:s=s.replace(marker,extra+marker)
p.write_text(s)
