plugins {
    id 'com.android.application'
}

android {
    namespace 'ch.piiwii.listy'
    compileSdk 35

    defaultConfig {
        applicationId 'ch.piiwii.listy'
        minSdk 26
        targetSdk 29
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
