plugins {
    id 'com.android.application'
}

android {
    namespace 'ch.piiwii.listy'
    compileSdk 35

    defaultConfig {
        applicationId 'ch.piiwii.listy'
        minSdk 26
        targetSdk 29
        versionCode 2
        versionName '1.1.0'
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
