plugins {
    id 'com.android.application'
}

android {
    namespace 'ch.piiwii.rabais'
    compileSdk 35

    defaultConfig {
        applicationId 'ch.piiwii.rabaisexpress'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '1.2.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
