package ch.piiwii.euroscan;
import org.json.*;import org.jsoup.Jsoup;import org.jsoup.nodes.Document;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.regex.*;
public class ResultsRepository {
    private static final String API="https://api-euromillions.nunofcguerreiro.com",SWISS="https://www.euromillions.ch/fr/euromillions/informations/r%C3%A9sultats/r%C3%A9sultats-gains.html";
    public DrawResult fetch(String date)throws Exception{DrawResult r=numbers(date);try{swiss(r);}catch(Exception ignored){}return r;} public DrawResult latest()throws Exception{DrawResult r=numbers(null);try{swiss(r);}catch(Exception ignored){}return r;}
    private DrawResult numbers(String date)throws Exception{String u=date==null||date.trim().isEmpty()?API+"/results/latest":API+"/results/date/"+URLEncoder.encode(date,"UTF-8");JSONObject o=new JSONObject(get(u));DrawResult r=new DrawResult();r.date=o.optString("date",date==null?"":date);JSONArray n=o.getJSONArray("numbers"),s=o.getJSONArray("stars");for(int i=0;i<n.length();i++)r.numbers.add(n.getInt(i));for(int i=0;i<s.length();i++)r.stars.add(s.getInt(i));Collections.sort(r.numbers);Collections.sort(r.stars);return r;}
    private void swiss(DrawResult r)throws Exception{Document d=Jsoup.connect(SWISS).userAgent("Mozilla/5.0 EuroScanCH/1.0").timeout(12000).get();String text=d.text().replace('’','\'');int p=text.toLowerCase(Locale.ROOT).indexOf("résultats & gains");if(p<0)p=0;String head=text.substring(p,Math.min(text.length(),p+1600));int found=0;for(int n:r.numbers)if(Pattern.compile("(?<!\\d)"+n+"(?!\\d)").matcher(head).find())found++;if(found<4)return;int start=text.indexOf("Nombre de numéros exacts");if(start<0)return;String b=text.substring(start,Math.min(text.length(),start+3500));Pattern line=Pattern.compile("(?m)(5|4|3|2|1)\\s*(?:\\+[^0-9]{0,20})?\\s+([0-9'’ ]+)\\s+([0-9'’ ]+[.,][0-9]{2})");Matcher m=line.matcher(b);List<Double> vals=new ArrayList<>();while(m.find()&&vals.size()<13){try{vals.add(Double.parseDouble(m.group(3).replace("'","").replace("’","").replace(" ","").replace(',','.')));}catch(Exception ignored){}}if(vals.size()==13){String[] keys={"5+2","5+1","5+0","4+2","4+1","3+2","4+0","2+2","3+1","3+0","1+2","2+1","2+0"};for(int i=0;i<keys.length;i++)r.chfPrizes.put(keys[i],vals.get(i));r.exactSwissPrizes=true;}}
    private String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(12000);c.setRequestProperty("User-Agent","EuroScanCH/1.0 Android");int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String l;while((l=r.readLine())!=null)b.append(l);}if(code<200||code>=300)throw new IOException("HTTP "+code);return b.toString();}
}
