using System.Text.Json;
namespace PiiWii.Documents.Services;

public static class AssistantExchangeService
{
    static string SessionsRoot=>Path.Combine(AppPaths.DataRoot,"Assistant","sessions");
    public sealed record Preview(int Proposed,int Ignored,List<string> Changes,string SessionId);

    public static string ExportBatch(string batchId)
    {
        var docs=DatabaseService.GetBatch(batchId);if(docs.Count==0)throw new InvalidOperationException("Le lot est vide.");Directory.CreateDirectory(SessionsRoot);var outbox=Path.Combine(AppPaths.DataRoot,"Assistant","outbox");Directory.CreateDirectory(outbox);var sessionId=Guid.NewGuid().ToString("N");var ids=docs.Select(d=>d.Id).ToArray();
        var session=new{sessionId,batchId,expiresAt=DateTime.UtcNow.AddHours(24),documentIds=ids};File.WriteAllText(Path.Combine(SessionsRoot,sessionId+".json"),JsonSerializer.Serialize(session));
        var path=Path.Combine(outbox,$"batch-{batchId}-{sessionId[..8]}.json");var payload=new{schema="piiwii-documents-assistant-v2",appVersion="0.14.0",sessionId,batchId,expiresAt=DateTime.UtcNow.AddHours(24),instructions="Return same sessionId and batchId with documents array. Only listed ids are accepted.",documents=docs.Select(d=>new{d.Id,d.Title,d.DocumentType,d.Category,d.Organization,d.Reference,d.Amount,d.Currency,d.DocumentDate,d.Status,d.Vehicle,d.Tags,d.Description,d.Confidence,d.AnalysisStatus,d.OriginalName,d.PageCount,d.OcrText}).ToArray()};File.WriteAllText(path,JsonSerializer.Serialize(payload,new JsonSerializerOptions{WriteIndented=true}));DatabaseService.AuditExternal("Utilisateur","Export lot pour assistant",null,$"lot={batchId}; session={sessionId}; docs={ids.Length}");return path;
    }

    public static Preview PreviewResults(string path)
    {
        using var jd=JsonDocument.Parse(File.ReadAllText(path));var root=jd.RootElement;var sessionId=root.TryGetProperty("sessionId",out var se)?se.GetString()??"":"";if(string.IsNullOrWhiteSpace(sessionId))throw new InvalidDataException("Résultat sans sessionId. Réexporte le lot avec la 0.14.0.");var allowed=LoadSession(sessionId,out var batchId);if(root.TryGetProperty("batchId",out var be)&&be.GetString()!=batchId)throw new InvalidDataException("Le résultat ne correspond pas au lot autorisé.");if(!root.TryGetProperty("documents",out var arr)||arr.ValueKind!=JsonValueKind.Array)throw new InvalidDataException("Tableau documents absent.");int proposed=0,ignored=0;var changes=new List<string>();foreach(var item in arr.EnumerateArray()){if(!item.TryGetProperty("id",out var ie)||!ie.TryGetInt64(out var id)||!allowed.Contains(id)){ignored++;continue;}var d=DatabaseService.Get(id);if(d==null){ignored++;continue;}var fields=new List<string>();Check("title",d.Title);Check("category",d.Category);Check("organization",d.Organization);Check("status",d.Status);if(fields.Count>0){proposed++;changes.Add($"#{id} {d.Title}: {string.Join(", ",fields)}");}void Check(string n,string old){if(item.TryGetProperty(n,out var x)&&x.ValueKind==JsonValueKind.String){var v=x.GetString()??"";if(v.Trim()!=old.Trim())fields.Add($"{n} → {v.Trim()}");}}}return new(proposed,ignored,changes,sessionId);
    }

    public static (int updated,int ignored,List<string> errors) ApplyResults(string path)
    {
        var errors=new List<string>();int updated=0,ignored=0;using var jd=JsonDocument.Parse(File.ReadAllText(path));var root=jd.RootElement;var sessionId=root.GetProperty("sessionId").GetString()??"";var allowed=LoadSession(sessionId,out var batchId);if(root.TryGetProperty("batchId",out var be)&&be.GetString()!=batchId)throw new InvalidDataException("Le résultat ne correspond pas au lot autorisé.");foreach(var item in root.GetProperty("documents").EnumerateArray())try{if(!item.TryGetProperty("id",out var ie)||!ie.TryGetInt64(out var id)||!allowed.Contains(id)){ignored++;continue;}var d=DatabaseService.Get(id);if(d==null){ignored++;continue;}Apply(d,item);DatabaseService.Update(d,"Assistant IA","Classement importé depuis session limitée");updated++;}catch(Exception ex){errors.Add(ex.Message);}try{File.Delete(Path.Combine(SessionsRoot,sessionId+".json"));}catch{}DatabaseService.AuditExternal("Assistant IA","Résultats appliqués",null,$"session={sessionId}; lot={batchId}; updated={updated}");return(updated,ignored,errors);
    }

    static HashSet<long> LoadSession(string id,out string batch){var p=Path.Combine(SessionsRoot,Path.GetFileName(id)+".json");if(!File.Exists(p))throw new InvalidDataException("Session inconnue ou déjà utilisée.");using var j=JsonDocument.Parse(File.ReadAllText(p));var r=j.RootElement;if(r.GetProperty("expiresAt").GetDateTime().ToUniversalTime()<=DateTime.UtcNow)throw new InvalidDataException("Session expirée.");batch=r.GetProperty("batchId").GetString()??"";return r.GetProperty("documentIds").EnumerateArray().Select(x=>x.GetInt64()).ToHashSet();}
    static void Apply(PiiWii.Documents.Models.DocumentRecord d,JsonElement i){string? S(string n)=>i.TryGetProperty(n,out var e)&&e.ValueKind==JsonValueKind.String?e.GetString():null;if(S("title")is{}a)d.Title=a.Trim();if(S("documentType")is{}b)d.DocumentType=b.Trim();if(S("category")is{}c)d.Category=c.Trim();if(S("organization")is{}e)d.Organization=e.Trim();if(S("reference")is{}f)d.Reference=f.Trim();if(S("currency")is{}g)d.Currency=g.Trim();if(S("status")is{}h)d.Status=h.Trim();if(S("vehicle")is{}v)d.Vehicle=v.Trim();if(S("tags")is{}t)d.Tags=t.Trim();if(S("description")is{}z)d.Description=z.Trim();if(i.TryGetProperty("amount",out var am)&&am.TryGetDecimal(out var av))d.Amount=av;if(S("documentDate")is{}ds&&DateTime.TryParse(ds,out var dv))d.DocumentDate=dv.Date;if(i.TryGetProperty("confidence",out var cf)&&cf.TryGetInt32(out var cv))d.Confidence=Math.Clamp(cv,0,100);else d.Confidence=Math.Max(85,d.Confidence);d.AnalysisStatus="Classé par assistant";}
}
