package ch.piiwii.listybridge;

import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.text.InputType;import android.view.View;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.text.DateFormat;import java.util.Date;

public class MainActivity extends Activity {
    private EditText pairing; private TextView status,last;
    @Override public void onCreate(Bundle b){super.onCreate(b);build();handleIntent(getIntent());refresh();}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handleIntent(i);}
    @Override protected void onResume(){super.onResume();refresh();}
    private void build(){getWindow().setStatusBarColor(Ui.NAVY);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(Ui.BG);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(Ui.dp(this,20),Ui.dp(this,24),Ui.dp(this,20),Ui.dp(this,32));box.addView(Ui.text(this,"ListY",30,Ui.NAVY,true));box.addView(Ui.text(this,"Migros / Cumulus Bridge",17,Color.DKGRAY,true));addSpace(box,18);status=Ui.text(this,"",16,Ui.NAVY,true);status.setPadding(Ui.dp(this,16),Ui.dp(this,15),Ui.dp(this,16),Ui.dp(this,15));status.setBackground(Ui.rounded(Color.WHITE,16,this));box.addView(status);addSpace(box,16);box.addView(Ui.text(this,"1 · Relier à ton ListY",19,Ui.NAVY,true));box.addView(Ui.text(this,"Dans ListY → Migros / Cumulus, génère la liaison puis ouvre-la avec cette application ou colle-la ici.",14,Color.DKGRAY,false));addSpace(box,8);pairing=new EditText(this);pairing.setHint("listybridge://pair?...");pairing.setSingleLine(false);pairing.setMinLines(2);pairing.setTextSize(13);pairing.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);pairing.setPadding(Ui.dp(this,14),Ui.dp(this,12),Ui.dp(this,14),Ui.dp(this,12));pairing.setBackground(Ui.rounded(Color.WHITE,12,this));box.addView(pairing);android.widget.Button save=Ui.button(this,"Enregistrer la liaison",false);save.setOnClickListener(v->{if(BridgeConfig.parseAndSave(this,pairing.getText().toString())){toast("Liaison enregistrée");ping();refresh();}else toast("Liaison invalide. Copie la liaison complète depuis ListY.");});box.addView(spaceParam(save,10));addSpace(box,20);box.addView(Ui.text(this,"2 · Connecter Migros",19,Ui.NAVY,true));box.addView(Ui.text(this,"Tu te connectes uniquement dans la page officielle Migros affichée dans l’application. ListY ne reçoit jamais ton mot de passe.",14,Color.DKGRAY,false));addSpace(box,10);android.widget.Button login=Ui.button(this,"Ouvrir Migros et synchroniser",true);login.setOnClickListener(v->{if(!BridgeConfig.paired(this)){toast("Relie d’abord ListY Bridge.");return;}startActivity(new Intent(this,MigrosLoginActivity.class));});box.addView(login);last=Ui.text(this,"",14,Color.DKGRAY,false);box.addView(spaceParam(last,12));addSpace(box,18);box.addView(Ui.text(this,"Le pont utilise les endpoints web Cumulus de Migros. Ils ne sont pas une API publique officielle et peuvent changer.",12,Color.GRAY,false));scroll.addView(box);setContentView(scroll);}
    private View spaceParam(View v,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=Ui.dp(this,top);v.setLayoutParams(p);return v;}private void addSpace(LinearLayout l,int dp){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,Ui.dp(this,dp)));l.addView(v);}private void handleIntent(Intent i){Uri u=i==null?null:i.getData();if(u!=null&&"listybridge".equals(u.getScheme())){String s=u.toString();pairing.setText(s);if(BridgeConfig.parseAndSave(this,s)){toast("ListY Bridge relié");ping();}}}private void ping(){new Thread(()->{try{BridgeHttp.ping(this);runOnUiThread(()->{toast("Liaison ListY reconnue");refresh();});}catch(Exception e){runOnUiThread(()->{toast(e.getMessage());refresh();});}}).start();}private void refresh(){boolean paired=BridgeConfig.paired(this);String ps=SecureStore.getPlain(this,"pair_status");status.setText(paired?("✓ ListY relié"+("ok".equals(ps)?" et vérifié":"")):"○ ListY n’est pas encore relié");String t=SecureStore.getPlain(this,"last_sync"),cnt=SecureStore.getPlain(this,"last_count");if(!t.isEmpty()){try{last.setText("Dernière synchro : "+DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(Long.parseLong(t)))+" · "+cnt+" coupon(s)");}catch(Exception e){last.setText("");}}else last.setText("Aucune synchronisation Cumulus réussie pour le moment.");}private void toast(String s){Toast.makeText(this,s==null?"":s,Toast.LENGTH_LONG).show();}
}
