package ch.piiwii.listybridge;

import android.app.Activity;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.webkit.CookieManager;import android.webkit.WebChromeClient;import android.webkit.WebResourceRequest;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;import android.widget.LinearLayout;import android.widget.TextView;import android.widget.Toast;import org.json.JSONArray;import org.json.JSONObject;

public class MigrosLoginActivity extends Activity {
    private static final String REDIRECT="https://www.migros.ch/m-login-silent-login-redirect.html";private WebView web;private TextView status;private String pendingCode="",pendingState="";private boolean waitingHome=false;
    @Override public void onCreate(Bundle b){super.onCreate(b);build();}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(Ui.dp(this,14),Ui.dp(this,12),Ui.dp(this,14),Ui.dp(this,10));head.setBackgroundColor(Ui.NAVY);head.addView(Ui.text(this,"Connexion Migros",20,Color.WHITE,true));status=Ui.text(this,"Connecte-toi normalement chez Migros, puis touche le bouton en bas.",12,Color.WHITE,false);head.addView(status);root.addView(head);web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(u.startsWith(REDIRECT)){captureRedirect(r.getUrl());return true;}return false;}@Override public void onPageFinished(WebView v,String url){if(waitingHome&&url.startsWith("https://www.migros.ch")){waitingHome=false;exchangeAndFetch();}}});root.addView(web,new LinearLayout.LayoutParams(-1,0,1));android.widget.Button done=Ui.button(this,"J’ai terminé → lire mes coupons",true);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(Ui.dp(this,12),Ui.dp(this,8),Ui.dp(this,12),Ui.dp(this,12));done.setLayoutParams(bp);done.setOnClickListener(v->startSilentAuth());root.addView(done);setContentView(root);web.loadUrl("https://www.migros.ch/fr/cumulus");}
    private void startSilentAuth(){if(web.getUrl()==null||!web.getUrl().startsWith("https://www.migros.ch")){status.setText("Reviens sur la page Migros après la connexion, puis réessaie.");web.loadUrl("https://www.migros.ch/fr/cumulus");return;}status.setText("Vérification de ta session Migros…");String js="(async()=>{try{const u='/authentication/public/v1/api/oauth/authorize?redirectUri='+encodeURIComponent('"+REDIRECT+"')+'&withLoginPrompt=false&claimType=LOGIN&authorizationNotRequired=true';const r=await fetch(u,{credentials:'include',headers:{Accept:'application/json'}});const j=await r.json();return JSON.stringify({ok:r.ok,url:j.url||''});}catch(e){return JSON.stringify({ok:false,error:String(e)})}})()";web.evaluateJavascript(js,val->{try{String txt=decodeJs(val);JSONObject j=new JSONObject(txt);String url=j.optString("url","");if(url.isEmpty()){status.setText("Session Migros introuvable. Vérifie que tu es bien connecté.");return;}web.loadUrl(url);}catch(Exception e){status.setText("Impossible de démarrer la liaison Migros : "+e.getMessage());}});}
    private void captureRedirect(Uri u){pendingCode=u.getQueryParameter("code");pendingState=u.getQueryParameter("state");if(pendingCode==null||pendingState==null){status.setText("Migros n’a pas renvoyé le code de session.");return;}waitingHome=true;web.loadUrl("https://www.migros.ch/fr/cumulus");}
    private void exchangeAndFetch(){status.setText("Lecture de tes coupons Cumulus…");String code=JSONObject.quote(pendingCode),state=JSONObject.quote(pendingState),redir=JSONObject.quote(REDIRECT);String js="(async()=>{try{const success='/authentication/public/v1/api/oauth/login-success?code='+encodeURIComponent("+code+")+'&state='+encodeURIComponent("+state+")+'&redirectUri='+encodeURIComponent("+redir+")+'&authorizationNotRequired=true';const sr=await fetch(success,{credentials:'include',headers:{Accept:'application/json'}});const sj=await sr.json();let token=sj.accessToken||sj.access_token||sj.token||'';token=String(token).replace(/^Bearer\\s+/i,'');if(!token)return JSON.stringify({ok:false,error:'Jeton Cumulus absent'});const cr=await fetch('/retentionapi/public/web/v1/cumulus-coupons',{credentials:'include',headers:{Authorization:'Bearer '+token,'migros-language':'fr','peer-id':'website-js-1143.0.0',Accept:'application/json'}});const body=await cr.text();return JSON.stringify({ok:cr.ok,status:cr.status,body});}catch(e){return JSON.stringify({ok:false,error:String(e)})}})()";web.evaluateJavascript(js,val->{try{JSONObject r=new JSONObject(decodeJs(val));if(!r.optBoolean("ok",false)){status.setText("Migros refuse la lecture : "+r.optString("error","HTTP "+r.optInt("status")));return;}JSONArray normalized=CouponNormalizer.normalize(r.optString("body","[]"));status.setText("Envoi de "+normalized.length()+" coupon(s) à ListY…");new Thread(()->{try{int n=BridgeHttp.pushCoupons(this,normalized);runOnUiThread(()->{Toast.makeText(this,n+" coupon(s) synchronisé(s) dans ListY",Toast.LENGTH_LONG).show();finish();});}catch(Exception e){runOnUiThread(()->status.setText("Erreur ListY : "+e.getMessage()));}}).start();}catch(Exception e){status.setText("Réponse Migros illisible : "+e.getMessage());}});}
    private static String decodeJs(String v)throws Exception{if(v==null||"null".equals(v))return"";return new JSONArray("["+v+"]").getString(0);}@Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
}
