name: Deliver PiiWii PDF 1.6.4
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deliver-piiwii-pdf-1.6.4.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: PiiWii-PDF-1.6.4
          path: _temp/PiiWii-PDF-1.6.4.apk
          retention-days: 1
          compression-level: 0
